### PR TITLE
Added Support for web (html, css, js, vue, svelte, tw) & php (php, hack)

### PR DESCRIPTION
**Pull request by steale-dot**
Added support as mentioned in the title.
Also willing to add linters etc... if wished!

maybe the implementation should look like this in the `module.fnl`

```lisp
(web +lint +format) ; the tubes
```

Thanks for this great project.

### CODE REVIEW

**Comment by shaunsingh** [comment]
Wonderful. I'll add listing support through https://github.com/mfussenegger/nvim-lint, and probably split the lsp module into a `tools.lsp` module and an `editor.diagnostics` module. After that it should be straghtforward to add the listing configs as well

> (web +lint +format) ; the tubes

For now, sadly we can only do `lang.web`, I haven't added support for module flags yet, though its coming in the future!

**Comment by shaunsingh** [comment]
I added support for linting under the `tools.diagnostics` module. Theres also support for formatting through `formatter.nvim` (in the `editor.format` module) so feel free to take a look at https://github.com/mhartington/formatter.nvim/tree/master/lua/formatter/filetypes and add formatting support for the languages you'd like

**Comment by shaunsingh** [comment]
I think you've got everything, but feel free to look through https://github.com/shaunsingh/nyoom.nvim/blob/main/docs/modules.md if you'd like.

**Comment by shaunsingh** [comment]
Note that the module syntax *slightly* changed to allow for module flags, feel free to gate additional functionality behind flags

**Comment by steale-dot** [comment]
Hey @shaunsingh,
Currently i can't work on it caused by
https://github.com/shaunsingh/oxocarbon.nvim/issues/9
Do you have any plans what might could resolve this?

**Comment by shaunsingh** [comment]
Not sure if you meant to close this but I moved the colorscheme back to lua/fennel in the main branch so everything should be good to go now

**Pull request merged**
